# 百度通用翻译API,不包含词典、tts语音合成等资源，如有相关需求请联系translate_api@baidu.com
# coding=utf-8

import http.client
import hashlib
import urllib
import random
import json
import time

appid = '20181128000240789'  # 填写你的appid
secretKey = '5pM_riBGZwfGJSS7vcMl'  # 填写你的密钥

words = ['AB',
         'ACTION',
         'ADD',
         'ADDRESS',
         'ALARM',
         'ALIAS',
         'ALTERATION',
         'APPLICATION',
         'ARCHIVE',
         'AREA',
         'ASSORT',
         'ATTR',
         'ATTR1',
         'ATTR2',
         'AUTHORITY',
         'BBU',
         'BELONG',
         'BM',
         'BRANCH',
         'BSC',
         'BTS',
         'BUILD',
         'BUILDING',
         'BUSINESS',
         'CAUSE',
         'CELL',
         'CHANNEL',
         'CHECK',
         'CHECKED',
         'CHILD',
         'CHILDREGION',
         'CHINA',
         'CLOG',
         'CODE',
         'COMMUNITY',
         'COMPANY',
         'COMPLAINT',
         'CONFIRMATION',
         'CONSTRUCT',
         'DELIVERY',
         'DESC',
         'DONE',
         'EQUIPMENT',
         'FINISH',
         'FULL',
         'ID',
         'IDENTIFIY',
         'INFO',
         'INSPECTION',
         'KIND',
         'LEVEL',
         'LIMIT',
         'NAME',
         'OPEN',
         'POINT',
         'PROJECT',
         'REGION',
         'SEGM',
         'SEQUENCE',
         'SHARING',
         'SIDE',
         'STATE',
         'STATUS',
         'TASK',
         'TIME',
         'TITLE',
         'TYPE',
         'USER',
         'START',
         'CONSTRUCTION',
         'MAN',
         'MODE',
         'COORDINATE',
         'COPY',
         'CRAFT',
         'ACCEPT',
         'CREATE',
         'OP',
         'CS',
         'FLAG',
         'CX',
         'REQUIREMENT',
         'CYCLE',
         'DATA',
         'COLLECTOR',
         'DATACOLLECT',
         'UNIT',
         'DEAL',
         'ORG',
         'DELAYED',
         'DELETE',
         'DEPARTMENT',
         'HEAD',
         'DEPLOYMENT',
         'DESIGN',
         'SITE',
         'VERIFY',
         'DESIGNATED',
         'CON',
         'DETAIL',
         'DEVIATION',
         'FROM',
         'DISPATCH',
         'SN',
         'DISTRICT',
         'DOORPLATE',
         'DX',
         'E',
         'SERIAL',
         'NUM',
         'END',
         'ENGINEERING',
         'PERIODS',
         'ENVIRONMENT',
         'REGISTER',
         'NUMBER',
         'MODEL',
         'POSITION',
         'SOURCE',
         'EVENT',
         'RECOVERY',
         'FACTORY',
         'FAULTCAUSE',
         'STR',
         'FEEDBACK',
         'FGS',
         'FILE',
         'FIRST',
         'RECEPTTIME',
         'FLOOR',
         'FLOW',
         'PATH',
         'TERMINATED',
         'GD',
         'GH',
         'GNB',
         'IDENTIFICATION',
         'GRADE',
         'GRAPH',
         'HEIGHT',
         'WIDTH',
         'HANG',
         'UP',
         'BEGIN',
         'MINUTES',
         'HEDAN',
         'WAY',
         'INTEGRATION',
         'INVEST',
         'ANALYZE',
         'CALCULATION',
         'INVESTMENT',
         'AMOUNT',
         'IS',
         'AGENCY',
         'BLUETOOTH',
         'CITY',
         'CL',
         'MESSAGE',
         'CONTINUE',
         'TRIDUUM',
         'HAVE',
         'EVALUATE',
         'HIDDEN',
         'TROUBLE',
         'NEW',
         'OK',
         'PASS',
         'TOWER',
         'PF',
         'QD',
         'SHARE',
         'SYN',
         'APPLY',
         'ISOFFSET',
         'IWM',
         'JAR',
         'JD',
         'LAT',
         'LNG',
         'LAN',
         'LATITUDE',
         'LEAVE',
         'LOCATION',
         'LONGITUDE',
         'LOSE',
         'MAIN',
         'MAJOR',
         'MANAGEMENT',
         'MAPX',
         'MAPY',
         'MARKER',
         'PLACE',
         'MATERIAL',
         'MATCHING',
         'MATERIALMAN',
         'MB',
         'MNT',
         'MOBILE',
         'MODIFY',
         'NE',
         'DN',
         'NET',
         'NOTES',
         'OBJECT',
         'OLD',
         'EQP',
         'NO',
         'SP',
         'OMC',
         'RECEIVED',
         'UID',
         'OPR',
         'OPTIMIZE',
         'ORDER',
         'THEME',
         'LEADER',
         'ORIG',
         'SEVERITY',
         'OWN',
         'PARENT',
         'WORK',
         'PHYSICAL',
         'PI',
         'RS',
         'PICK',
         'PLAN',
         'REL',
         'PLMN',
         'POLE',
         'LINE',
         'POS',
         'X',
         'Y',
         'POSITIONDUTY',
         'PRIMARY',
         'PRINCIPAL',
         'PRIORITY',
         'SORT',
         'PRO',
         'GET',
         'IMPL',
         'SMALL',
         'PROP',
         'CHAR',
         'PROPERTY',
         'PROVICE',
         'PURCHASE',
         'R',
         'REAL',
         'RELIEF',
         'REMOVE',
         'RES',
         'RESOURCE',
         'RESTORETIME',
         'RETURN',
         'ROOM',
         'ROOT',
         'RRU',
         'OR',
         'SC',
         'SCENE',
         'SINGLESITE',
         'SPECIFIC',
         'PROBLEM',
         'STATION',
         'STAY',
         'STREET',
         'SUB',
         'CIR',
         'SPE',
         'EQU',
         'SA',
         'SUBSTATION',
         'SUGGESTED',
         'SUPER',
         'SUPERVISOR',
         'TERRITORIAL',
         'NATURE',
         'TO',
         'B',
         'ACCEPTANCE',
         'TOWNFLAG',
         'TRANSFER',
         'UPLOAD',
         'USAGE',
         'USE',
         'WANGYUN',
         'WEIGHTED',
         'RATING',
         'WF',
         'WY',
         'YH',
         'Z',
         'ZX',
         'UPDATE'
         ]


def get_trans_result(q: str, fromLang: str = 'auto', toLang: str = 'zh'):
    httpClient = None
    myurl = '/api/trans/vip/translate'
    salt = random.randint(32768, 65536)
    sign = appid + q + str(salt) + secretKey
    sign = hashlib.md5(sign.encode()).hexdigest()
    myurl = myurl + '?appid=' + appid + '&q=' + urllib.parse.quote(
        q) + '&from=' + fromLang + '&to=' + toLang + '&salt=' + str(
        salt) + '&sign=' + sign

    try:
        httpClient = http.client.HTTPConnection('api.fanyi.baidu.com')
        httpClient.request('GET', myurl)

        # response是HTTPResponse对象
        response = httpClient.getresponse()
        # print(response)
        result_all = response.read().decode("utf-8")
        result = json.loads(result_all)
        return result['trans_result'][0]['dst']
    except Exception as e:
        return ''
    finally:
        if httpClient:
            httpClient.close()


if __name__ == '__main__':
    for word in words:
        print(word+'\t'+get_trans_result(word))
        time.sleep(0.5)
